version: "3"
services:
  app:
    image: pudding/docker-web:docker-web-apache-solr-app-20231101-0057
    tty: true
    ports:
      - "8983:8983"
    volumes: 
      - "[SOURCE]/docker-web-Apache-Solr:/var/solr/data/collection/conf"