version: "3"
services:
  app:
    image: pudding/docker-web:docker-web-apache-solr-app-20231111.173446
    tty: true
    ports:
      - "8983:8983"
    environment:
      - LOCAL_VOLUMN_PATH=/var/solr/data/collection/conf/
      - CONTAINER_NAME=docker-web-apache-solr-app
    volumes: 
      - "__SOURCE__/docker-web-Apache-Solr:/var/solr/data/collection/conf"