version: "3"
services:
  app:
    image: pudding/docker-web:docker-web-apache-solr-app-20231101-0068
    tty: true
    ports:
      - "8983:8983"
    environment:
      - LOCAL_VOLUMN_PATH=/var/solr/data/collection/conf
    volumes: 
      - "__SOURCE__/docker-web-Apache-Solr:/var/solr/data/collection/conf"